### ISSUE TITLE
Node.jsのバージョンについて

### ISSUE THREAD

**Issue by suzuki84g** [franknyro/octoling-girl-bot#13]
## このISSUEの背景

- （本番/開発）環境が分からない
- nodejsよく分かってないから、俺がどこを見れば書いてあるのかを分かっていない
  `packege-lock.json`叩けば入るの？
- helokuの仕様も分かってない（nodeの指定とかどこ見てんだろ）

## やりたいこと

- 開発環境を立てたい

## それに対してやるべきこと

- node.jsの動作環境の開発環境をどこかに明記する。
- その他importしてる依存packageが良く分からん。
- なんかその辺りのこと教えて下さい。

**Comment by franknyro** [comment]
## node.js のバージョンについて
- ローカルの開発環境は 10.14.2 です（少し古いです）。
- 本番環境 の [Heroku は 10.x と 12.x と14.x をサポートしています。](https://devcenter.heroku.com/articles/nodejs-support)

## 依存パッケージについて
- `package.json` と `package-lock.json` があれば、`npm ci` で環境が再現できるはずです。
- 詳しくは `npm ci` 関連でググってみてください。

**Comment by suzuki84g** [comment]
回答ありがとうー助かる。
`npm ci`知らんかった、軽くググった感じ、installの代替か。
node.jsのバージョンは`npm ci`では揃わないから手動で合わせる必要があるんだな。
（なのでdockerで開発環境仕込むか、readmeにでも記載しておく感じだな、この規模だと全然後者で良いと思うが）
時間見つけて環境構築からやってみます、ありがとうー。
